FROM tiangolo/uvicorn-gunicorn-machine-learning:python3.7

COPY ./app /app

RUN apt update && \
    apt install -y postgresql-client

COPY environment.yml .
RUN conda env create -f environment.yml

# RUN conda active myenv
SHELL ["conda", "run", "-n", "myenv", "/bin/bash", "-c"]
# SHELL ["conda", "run", "-n", "myenv", "/bin/bash", "-c", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
# RUN echo "WOW"
# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]

# COPY . .
# ENTRYPOINT ["conda", "run", "-n", "myenv", "/bin/bash", "-c"]