name: toxenv
channels:
  - conda-forge
dependencies:
  - python=3.7
  - alembic=1.4.2
  - Authlib=0.14.3
  - fastapi=0.58
  - httpx=0.12.1
  - ipython=7.14.0
  - itsdangerous=1.1.0
  - Jinja2=2.11.2
  - psycopg2=2.8.5
  - pytest=5.4.2
  - requests=2.23.0
  - SQLAlchemy=1.3.17
  - starlette=0.13.4
  - uvicorn=0.11.3
  - pydantic=1.5.1
  - rdkit=2020.03.3
  - joblib=0.14.1
  - scikit-learn=0.23.1
#  - requests=2.23.0
